"""initial schema

Revision ID: c2a8cdfb7615
Revises: 
Create Date: 2026-08-03 14:29:43.535030
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.types

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# The full-text index is a virtual table, so it is created by hand rather than
# by autogenerate. ``unicode61 remove_diacritics 2`` makes "cafe" match "café",
# which matters for a bilingual (EN/ES) corpus.
FTS_CREATE = """
CREATE VIRTUAL TABLE search_index USING fts5(
    ref_type UNINDEXED,
    ref_id UNINDEXED,
    source_id UNINDEXED,
    kind UNINDEXED,
    title,
    body,
    tokenize = 'unicode61 remove_diacritics 2'
)
"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('collection',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('comparison',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subject_type', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedding',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('norm', app.types.DecimalText(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_type', 'ref_id', 'model', name='uq_embedding_ref')
    )
    with op.batch_alter_table('embedding', schema=None) as batch_op:
        batch_op.create_index('ix_embedding_model', ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_embedding_source_id'), ['source_id'], unique=False)

    op.create_table('entity',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases_json', sa.JSON(), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'normalized_name', name='uq_entity_kind_name')
    )
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index('ix_entity_kind', ['kind'], unique=False)

    op.create_table('generation',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=48), nullable=False),
    sa.Column('model', sa.String(length=160), nullable=False),
    sa.Column('operation', sa.String(length=48), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('output', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_batch',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_object',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('generated_by', sa.String(length=160), nullable=True),
    sa.Column('generation_id', sa.String(length=36), nullable=True),
    sa.Column('review_due_on', app.types.IsoDate(length=10), nullable=True),
    sa.Column('resolved_at', app.types.UtcDateTime(length=32), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_object', schema=None) as batch_op:
        batch_op.create_index('ix_knowledge_kind_status', ['kind', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_object_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_object_origin'), ['origin'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_object_review_due_on'), ['review_due_on'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_object_status'), ['status'], unique=False)

    op.create_table('link',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('from_type', sa.String(length=32), nullable=False),
    sa.Column('from_id', sa.String(length=36), nullable=False),
    sa.Column('to_type', sa.String(length=32), nullable=False),
    sa.Column('to_id', sa.String(length=36), nullable=False),
    sa.Column('relation', sa.String(length=48), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_type', 'from_id', 'to_type', 'to_id', 'relation', name='uq_link_edge')
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index('ix_link_from', ['from_type', 'from_id'], unique=False)
        batch_op.create_index('ix_link_to', ['to_type', 'to_id'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('collection_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('collection_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'target_type', 'target_id', name='uq_collection_item')
    )
    op.create_table('comparison_dimension',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('higher_is_better', sa.Boolean(), nullable=False),
    sa.Column('weight', app.types.DecimalText(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparison.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_subject',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparison.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_id', 'target_type', 'target_id', name='uq_comparison_subject')
    )
    op.create_table('dossier',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('subject_kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('overview', sa.Text(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('bull_case', sa.Text(), nullable=False),
    sa.Column('bear_case', sa.Text(), nullable=False),
    sa.Column('risks', sa.Text(), nullable=False),
    sa.Column('open_questions', sa.Text(), nullable=False),
    sa.Column('primary_entity_id', sa.String(length=36), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['primary_entity_id'], ['entity.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dossier_status'), ['status'], unique=False)

    op.create_table('source',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('publisher', sa.String(length=300), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('published_on', app.types.IsoDate(length=10), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('original_filename', sa.String(length=400), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=160), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('extraction_warnings', sa.JSON(), nullable=False),
    sa.Column('detected_metadata', sa.JSON(), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('imported_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('reviewed_at', app.types.UtcDateTime(length=32), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('duplicate_of_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batch.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_text_hash'), ['text_hash'], unique=False)

    op.create_table('tagging',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'target_type', 'target_id', name='uq_tagging')
    )
    with op.batch_alter_table('tagging', schema=None) as batch_op:
        batch_op.create_index('ix_tagging_target', ['target_type', 'target_id'], unique=False)

    op.create_table('document',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('locator_json', sa.JSON(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'ordinal', name='uq_document_source_ordinal')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('ix_document_source_ordinal', ['source_id', 'ordinal'], unique=False)

    op.create_table('dossier_claim',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('generated_by', sa.String(length=160), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dossier_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('section', sa.String(length=48), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dossier_id', 'target_type', 'target_id', name='uq_dossier_item')
    )
    with op.batch_alter_table('dossier_item', schema=None) as batch_op:
        batch_op.create_index('ix_dossier_item_target', ['target_type', 'target_id'], unique=False)

    op.create_table('entity_mention',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('detector', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'source_id', name='uq_entity_mention')
    )
    with op.batch_alter_table('entity_mention', schema=None) as batch_op:
        batch_op.create_index('ix_entity_mention_source', ['source_id'], unique=False)

    op.create_table('timeline_event',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dossier_id', sa.String(length=36), nullable=False),
    sa.Column('occurred_on', app.types.IsoDate(length=10), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossier.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_event', schema=None) as batch_op:
        batch_op.create_index('ix_timeline_dossier_date', ['dossier_id', 'occurred_on'], unique=False)

    op.create_table('excerpt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('locator_json', sa.JSON(), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('created_via', sa.String(length=64), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('excerpt', schema=None) as batch_op:
        batch_op.create_index('ix_excerpt_source', ['source_id', 'char_start'], unique=False)

    op.create_table('claim_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('claim_id', sa.String(length=36), nullable=False),
    sa.Column('excerpt_id', sa.String(length=36), nullable=True),
    sa.Column('source_id', sa.String(length=36), nullable=True),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['dossier_claim.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['excerpt_id'], ['excerpt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comparison_cell',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('comparison_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('dimension_id', sa.String(length=36), nullable=False),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('numeric_value', app.types.DecimalText(), nullable=True),
    sa.Column('boolean_value', sa.Boolean(), nullable=True),
    sa.Column('excerpt_id', sa.String(length=36), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.Column('updated_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['comparison.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dimension_id'], ['comparison_dimension.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['excerpt_id'], ['excerpt.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['comparison_subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'dimension_id', name='uq_comparison_cell')
    )
    op.create_table('knowledge_excerpt',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('knowledge_id', sa.String(length=36), nullable=False),
    sa.Column('excerpt_id', sa.String(length=36), nullable=False),
    sa.Column('stance', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', app.types.UtcDateTime(length=32), nullable=False),
    sa.ForeignKeyConstraint(['excerpt_id'], ['excerpt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge_object.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_id', 'excerpt_id', name='uq_knowledge_excerpt')
    )
    # ### end Alembic commands ###
    op.execute(FTS_CREATE)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS search_index")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_excerpt')
    op.drop_table('comparison_cell')
    op.drop_table('claim_evidence')
    with op.batch_alter_table('excerpt', schema=None) as batch_op:
        batch_op.drop_index('ix_excerpt_source')

    op.drop_table('excerpt')
    with op.batch_alter_table('timeline_event', schema=None) as batch_op:
        batch_op.drop_index('ix_timeline_dossier_date')

    op.drop_table('timeline_event')
    with op.batch_alter_table('entity_mention', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_mention_source')

    op.drop_table('entity_mention')
    with op.batch_alter_table('dossier_item', schema=None) as batch_op:
        batch_op.drop_index('ix_dossier_item_target')

    op.drop_table('dossier_item')
    op.drop_table('dossier_claim')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('ix_document_source_ordinal')

    op.drop_table('document')
    with op.batch_alter_table('tagging', schema=None) as batch_op:
        batch_op.drop_index('ix_tagging_target')

    op.drop_table('tagging')
    with op.batch_alter_table('source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_text_hash'))
        batch_op.drop_index(batch_op.f('ix_source_status'))
        batch_op.drop_index(batch_op.f('ix_source_kind'))
        batch_op.drop_index(batch_op.f('ix_source_is_demo'))
        batch_op.drop_index(batch_op.f('ix_source_content_hash'))

    op.drop_table('source')
    with op.batch_alter_table('dossier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dossier_status'))

    op.drop_table('dossier')
    op.drop_table('comparison_subject')
    op.drop_table('comparison_dimension')
    op.drop_table('collection_item')
    op.drop_table('tag')
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index('ix_link_to')
        batch_op.drop_index('ix_link_from')

    op.drop_table('link')
    with op.batch_alter_table('knowledge_object', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_object_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_object_review_due_on'))
        batch_op.drop_index(batch_op.f('ix_knowledge_object_origin'))
        batch_op.drop_index(batch_op.f('ix_knowledge_object_kind'))
        batch_op.drop_index('ix_knowledge_kind_status')

    op.drop_table('knowledge_object')
    op.drop_table('import_batch')
    op.drop_table('generation')
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_kind')

    op.drop_table('entity')
    with op.batch_alter_table('embedding', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_source_id'))
        batch_op.drop_index('ix_embedding_model')

    op.drop_table('embedding')
    op.drop_table('comparison')
    op.drop_table('collection')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
